# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze currencyCode, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop
- release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@7.3.9
    npm install
    npm run prod
  displayName: 'npm install and build'

# THis may go away perhaps overkill if the "publish" bit below works, just different than I'm used to
# - script: |
#     ./zip-deploy.sh
#   displayName: 'release to azure artifacts'

- publish: $(System.DefaultWorkingDirectory)/dist
  artifact: Spa-develop
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

- publish: $(System.DefaultWorkingDirectory)/dist
  artifact: Spa-release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
