export const appRoutePaths = {
    changePassword: "change-password",
    companyDashboard: "company/:id/dashboard",
    companyDocuments: "company/:id/documents",
    companyFinancials: "company/:id/financials",
    companyInfo: "company/:id/info",
    companyInitiatives: "company/:id/initiatives",
    companyNotes: "company/:id/notes",
    companyValuation: "company/:id/valuation",
    login: "login",
    portfolioCalendarView: "portfolio-calendar-view",
    portfolioDashboard: "portfolio-dashboard",
    portfolioDocuments: "portfolio-documents",
    portfolioFinancials: "portfolio-financials",
    portfolioInitiatives: "portfolio-initiatives",
    portfolioListing: "portfolio-listing",
    portfolioMapView: "portfolio-map-view",
    register: "register",
    takeaways: "company/:id/takeaways"
};
