/**
 *
 * Note: This env_config may be used as a local-dev fallback for a 'config.js' that will contain an
 * equivalent env_config var for upper environments, which is generated by the build system.
 *
 * If y'all don't like this we can change to a strict "overwrite" mechanism and always rely
 * on a single file name config.js.
 */

/**
 *
 * Valid environment values
    'development'
    'dockerdev'
    'ci'
    'testing'
    'staging'
    'production'
 */
env_config = {
    "env": "development",
    "clientId": "5694e2d0-946a-4fb3-8864-3e0914280d03",
    "apiUrl": "https://prism-dev-api-management.azure-api.net/latest/"
};

